# THIS YAML FILE IS FOR THE DEV-EXTERNAL ENVIRONMENT PIPELINE ONLY
# USED WHEN THE DEVELOPER WANTS TO SPIN A NEW ENVIRONMENT WITH A CUSTOM NAME

pr: none
trigger: none

variables:
  - template: variables.yml

stages:
  - template: templates/stages/ci-cd-release-stages.yml
    parameters:
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      artifactName: $(artifactName)
      applicationName: $(applicationName) # From variable group
      deploymentEnvironmentType: $(deploymentEnvironmentType)
      environmentLabel: external  # Label defines what environment/service connection will be used
      externalEnvironment: $(environment)
