# THIS YAML FILE IS FOR THE QA-UAT/STAGE-PROD ENVIRONMENTS PIPELINE ONLY

pr: none
trigger:
  batch: true
  branches:
    include:
    - release/*

variables:
  - template: variables.yml

stages:
  - template: templates/stages/ci-cd-release-stages.yml
    parameters:
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      artifactName: $(artifactName)
      applicationName: $(applicationName) # From variable group
      deploymentEnvironmentType: $(deploymentEnvironmentType)
      environmentLabel: prod  # Label defines what environment/service connection will be used